import type { Metadata } from "next";
import { Geist, Geist_Mono, Mona_Sans, Roboto_Mono, Work_Sans, Space_Mono } from "next/font/google";
import "./globals.css";
import { AppProviderComp } from "@/components/useContext/AppContext";

const geistSans = Geist({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Work_Sans({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function ClientLayout({ children }: { children: React.ReactNode }) {
  return (
    <AppProviderComp>
      {children}
      {/* <Toaster position="top-right" /> */}
    </AppProviderComp>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.className} antialiased`}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
